version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      # Now mapping the entire assets folder
      - assets_data:/var/www/html/assets/ 
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    environment:
      # Pulling credentials securely from .env file
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: mysql:9.1
    restart: always
    environment:
      # Pulling MySQL setup instructions securely from .env file
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      # Protects actual database data
      - db_data:/var/lib/mysql
      - ./Backend/database_file/geargo.sql:/docker-entrypoint-initdb.d/init.sql

# Declaring the named volumes so Docker knows to create them
volumes:
  db_data:
  assets_data:w