version: '3.8'

services:
  web:
    build: .
    restart: always # Keeps site online if the server reboots
    ports:
      - "8080:80" # change to 80:80 if domain is used
    volumes:
      # ONLY mapping the uploads folder to protect user data from restarts
      - uploads_data:/var/www/html/assets/uploads/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: mysql:9.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # This will automatically set up database on the new cloud server
      - ./Backend/database_file/geargo.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
  uploads_data: